<?php namespace Pyro\FieldType;

use Pyro\Module\Streams\FieldType\FieldTypeAbstract;

class Phone extends FieldTypeAbstract
{
    /**
     * Field type slug
     *
     * @var string
     */
    public $field_type_slug = 'phone';

    /**
     * BD col type
     *
     * @var string
     */
    public $db_col_type = 'string';

    /**
     * Version
     *
     * @var string
     */
    public $version = '1.1';

    /**
     * Field type author information
     *
     * @var array
     */
    public $author = array(
        'name' => 'Ryan Thompson',
        'url'  => 'http://www.aiwebsystems.com/'
    );

    /**
     * Country codes
     *
     * @var array
     */
    protected $countryCodes = array(
        array(
            'country'      => 'Afghanistan',
            'iso_2'        => 'AF',
            'calling_code' => '+93',
            'option'       => 'Afghanistan +93',
            'html'         => '<img class="flag flag-af"/> Afghanistan +93',
        ),
        array(
            'country'      => 'Albania',
            'iso_2'        => 'AL',
            'calling_code' => '+355',
            'option'       => 'Albania +355',
            'html'         => '<img class="flag flag-al"/> Albania +355',
        ),
        array(
            'country'      => 'Algeria',
            'iso_2'        => 'DZ',
            'calling_code' => '+213',
            'option'       => 'Algeria +213',
            'html'         => '<img class="flag flag-dz"/> Algeria +213',
        ),
        array(
            'country'      => 'American Samoa',
            'iso_2'        => 'AS',
            'calling_code' => '+1684',
            'option'       => 'American Samoa +1684',
            'html'         => '<img class="flag flag-as"/> American Samoa +1684',
        ),
        array(
            'country'      => 'Andorra',
            'iso_2'        => 'AD',
            'calling_code' => '+376',
            'option'       => 'Andorra +376',
            'html'         => '<img class="flag flag-ad"/> Andorra +376',
        ),
        array(
            'country'      => 'Angola',
            'iso_2'        => 'AO',
            'calling_code' => '+244',
            'option'       => 'Angola +244',
            'html'         => '<img class="flag flag-ao"/> Angola +244',
        ),
        array(
            'country'      => 'Anguilla',
            'iso_2'        => 'AI',
            'calling_code' => '+1264',
            'option'       => 'Anguilla +1264',
            'html'         => '<img class="flag flag-ai"/> Anguilla +1264',
        ),
        array(
            'country'      => 'Antigua and Barbuda',
            'iso_2'        => 'AG',
            'calling_code' => '+1268',
            'option'       => 'Antigua and Barbuda +1268',
            'html'         => '<img class="flag flag-ag"/> Antigua and Barbuda +1268',
        ),
        array(
            'country'      => 'Argentina',
            'iso_2'        => 'AR',
            'calling_code' => '+54',
            'option'       => 'Argentina +54',
            'html'         => '<img class="flag flag-ar"/> Argentina +54',
        ),
        array(
            'country'      => 'Armenia',
            'iso_2'        => 'AM',
            'calling_code' => '+374',
            'option'       => 'Armenia +374',
            'html'         => '<img class="flag flag-am"/> Armenia +374',
        ),
        array(
            'country'      => 'Aruba',
            'iso_2'        => 'AW',
            'calling_code' => '+297',
            'option'       => 'Aruba +297',
            'html'         => '<img class="flag flag-aw"/> Aruba +297',
        ),
        array(
            'country'      => 'Ascension Island',
            'iso_2'        => 'AC',
            'calling_code' => '+247',
            'option'       => 'Ascension Island +247',
            'html'         => '<img class="flag flag-ac"/> Ascension Island +247',
        ),
        array(
            'country'      => 'Australia',
            'iso_2'        => 'AU',
            'calling_code' => '+61',
            'option'       => 'Australia +61',
            'html'         => '<img class="flag flag-au"/> Australia +61',
        ),
        array(
            'country'      => 'Austria',
            'iso_2'        => 'AT',
            'calling_code' => '+43',
            'option'       => 'Austria +43',
            'html'         => '<img class="flag flag-at"/> Austria +43',
        ),
        array(
            'country'      => 'Azerbaijan',
            'iso_2'        => 'AZ',
            'calling_code' => '+994',
            'option'       => 'Azerbaijan +994',
            'html'         => '<img class="flag flag-az"/> Azerbaijan +994',
        ),
        array(
            'country'      => 'Bahamas',
            'iso_2'        => 'BS',
            'calling_code' => '+1242',
            'option'       => 'Bahamas +1242',
            'html'         => '<img class="flag flag-bs"/> Bahamas +1242',
        ),
        array(
            'country'      => 'Bahrain',
            'iso_2'        => 'BH',
            'calling_code' => '+973',
            'option'       => 'Bahrain +973',
            'html'         => '<img class="flag flag-bh"/> Bahrain +973',
        ),
        array(
            'country'      => 'Bangladesh',
            'iso_2'        => 'BD',
            'calling_code' => '+880',
            'option'       => 'Bangladesh +880',
            'html'         => '<img class="flag flag-bd"/> Bangladesh +880',
        ),
        array(
            'country'      => 'Barbados',
            'iso_2'        => 'BB',
            'calling_code' => '+1246',
            'option'       => 'Barbados +1246',
            'html'         => '<img class="flag flag-bb"/> Barbados +1246',
        ),
        array(
            'country'      => 'Belarus',
            'iso_2'        => 'BY',
            'calling_code' => '+375',
            'option'       => 'Belarus +375',
            'html'         => '<img class="flag flag-by"/> Belarus +375',
        ),
        array(
            'country'      => 'Belgium',
            'iso_2'        => 'BE',
            'calling_code' => '+32',
            'option'       => 'Belgium +32',
            'html'         => '<img class="flag flag-be"/> Belgium +32',
        ),
        array(
            'country'      => 'Belize',
            'iso_2'        => 'BZ',
            'calling_code' => '+501',
            'option'       => 'Belize +501',
            'html'         => '<img class="flag flag-bz"/> Belize +501',
        ),
        array(
            'country'      => 'Benin',
            'iso_2'        => 'BJ',
            'calling_code' => '+229',
            'option'       => 'Benin +229',
            'html'         => '<img class="flag flag-bj"/> Benin +229',
        ),
        array(
            'country'      => 'Bermuda',
            'iso_2'        => 'BM',
            'calling_code' => '+1441',
            'option'       => 'Bermuda +1441',
            'html'         => '<img class="flag flag-bm"/> Bermuda +1441',
        ),
        array(
            'country'      => 'Bhutan',
            'iso_2'        => 'BT',
            'calling_code' => '+975',
            'option'       => 'Bhutan +975',
            'html'         => '<img class="flag flag-bt"/> Bhutan +975',
        ),
        array(
            'country'      => 'Bolivia',
            'iso_2'        => 'BO',
            'calling_code' => '+591',
            'option'       => 'Bolivia +591',
            'html'         => '<img class="flag flag-bo"/> Bolivia +591',
        ),
        array(
            'country'      => 'Bosnia and Herzegovina',
            'iso_2'        => 'BA',
            'calling_code' => '+387',
            'option'       => 'Bosnia and Herzegovina +387',
            'html'         => '<img class="flag flag-ba"/> Bosnia and Herzegovina +387',
        ),
        array(
            'country'      => 'Botswana',
            'iso_2'        => 'BW',
            'calling_code' => '+267',
            'option'       => 'Botswana +267',
            'html'         => '<img class="flag flag-bw"/> Botswana +267',
        ),
        array(
            'country'      => 'Brazil',
            'iso_2'        => 'BR',
            'calling_code' => '+55',
            'option'       => 'Brazil +55',
            'html'         => '<img class="flag flag-br"/> Brazil +55',
        ),
        array(
            'country'      => 'Brunei',
            'iso_2'        => 'BN',
            'calling_code' => '+673',
            'option'       => 'Brunei +673',
            'html'         => '<img class="flag flag-bn"/> Brunei +673',
        ),
        array(
            'country'      => 'Bulgaria',
            'iso_2'        => 'BG',
            'calling_code' => '+359',
            'option'       => 'Bulgaria +359',
            'html'         => '<img class="flag flag-bg"/> Bulgaria +359',
        ),
        array(
            'country'      => 'Burkina Faso',
            'iso_2'        => 'BF',
            'calling_code' => '+226',
            'option'       => 'Burkina Faso +226',
            'html'         => '<img class="flag flag-bf"/> Burkina Faso +226',
        ),
        array(
            'country'      => 'Burundi',
            'iso_2'        => 'BI',
            'calling_code' => '+257',
            'option'       => 'Burundi +257',
            'html'         => '<img class="flag flag-bi"/> Burundi +257',
        ),
        array(
            'id'           => 'KH+855',
            'country'      => 'Cambodia',
            'iso_2'        => 'KH',
            'calling_code' => '+855',
            'option'       => 'Cambodia +855',
            'html'         => '<img class="flag flag-kh"/> Cambodia +855',
        ),
        array(
            'id'           => 'CM+237',
            'country'      => 'Cameroon',
            'iso_2'        => 'CM',
            'calling_code' => '+237',
            'option'       => 'Cameroon +237',
            'html'         => '<img class="flag flag-cm"/> Cameroon +237',
        ),
        array(
            'id'           => 'CA+1',
            'country'      => 'Canada',
            'iso_2'        => 'CA',
            'calling_code' => '+1',
            'option'       => 'Canada +1',
            'html'         => '<img class="flag flag-ca"/> Canada +1',
        ),
        array(
            'id'           => 'CV+238',
            'country'      => 'Cape Verde',
            'iso_2'        => 'CV',
            'calling_code' => '+238',
            'option'       => 'Cape Verde +238',
            'html'         => '<img class="flag flag-cv"/> Cape Verde +238',
        ),
        array(
            'id'           => 'KY+1345',
            'country'      => 'Cayman Islands',
            'iso_2'        => 'KY',
            'calling_code' => '+1345',
            'option'       => 'Cayman Islands +1345',
            'html'         => '<img class="flag flag-ky"/> Cayman Islands +1345',
        ),
        array(
            'id'           => 'CF+236',
            'country'      => 'Central African Republic',
            'iso_2'        => 'CF',
            'calling_code' => '+236',
            'option'       => 'Central African Republic +236',
            'html'         => '<img class="flag flag-cf"/> Central African Republic +236',
        ),
        array(
            'id'           => 'TD+235',
            'country'      => 'Chad',
            'iso_2'        => 'TD',
            'calling_code' => '+235',
            'option'       => 'Chad +235',
            'html'         => '<img class="flag flag-td"/> Chad +235',
        ),
        array(
            'id'           => 'CL+56',
            'country'      => 'Chile',
            'iso_2'        => 'CL',
            'calling_code' => '+56',
            'option'       => 'Chile +56',
            'html'         => '<img class="flag flag-cl"/> Chile +56',
        ),
        array(
            'id'           => 'CN+86',
            'country'      => 'China',
            'iso_2'        => 'CN',
            'calling_code' => '+86',
            'option'       => 'China +86',
            'html'         => '<img class="flag flag-cn"/> China +86',
        ),
        array(
            'id'           => 'CO+57',
            'country'      => 'Colombia',
            'iso_2'        => 'CO',
            'calling_code' => '+57',
            'option'       => 'Colombia +57',
            'html'         => '<img class="flag flag-co"/> Colombia +57',
        ),
        array(
            'id'           => 'KM+269',
            'country'      => 'Comoros',
            'iso_2'        => 'KM',
            'calling_code' => '+269',
            'option'       => 'Comoros +269',
            'html'         => '<img class="flag flag-km"/> Comoros +269',
        ),
        array(
            'id'           => 'CG+242',
            'country'      => 'Congo',
            'iso_2'        => 'CG',
            'calling_code' => '+242',
            'option'       => 'Congo +242',
            'html'         => '<img class="flag flag-cg"/> Congo +242',
        ),
        array(
            'id'           => 'CD+243',
            'country'      => 'Congo Democratic Republic',
            'iso_2'        => 'CD',
            'calling_code' => '+243',
            'option'       => 'Congo Democratic Republic +243',
            'html'         => '<img class="flag flag-cd"/> Congo Democratic Republic +243',
        ),
        array(
            'id'           => 'CK+682',
            'country'      => 'Cook Islands',
            'iso_2'        => 'CK',
            'calling_code' => '+682',
            'option'       => 'Cook Islands +682',
            'html'         => '<img class="flag flag-ck"/> Cook Islands +682',
        ),
        array(
            'id'           => 'CR+506',
            'country'      => 'Costa Rica',
            'iso_2'        => 'CR',
            'calling_code' => '+506',
            'option'       => 'Costa Rica +506',
            'html'         => '<img class="flag flag-cr"/> Costa Rica +506',
        ),
        array(
            'id'           => 'CI+225',
            'country'      => 'Cote d\'Ivoire',
            'iso_2'        => 'CI',
            'calling_code' => '+225',
            'option'       => 'Cote d\'Ivoire +225',
            'html'         => '<img class="flag flag-ci"/> Cote d\'Ivoire +225',
        ),
        array(
            'id'           => 'HR+385',
            'country'      => 'Croatia',
            'iso_2'        => 'HR',
            'calling_code' => '+385',
            'option'       => 'Croatia +385',
            'html'         => '<img class="flag flag-hr"/> Croatia +385',
        ),
        array(
            'id'           => 'CU+53',
            'country'      => 'Cuba',
            'iso_2'        => 'CU',
            'calling_code' => '+53',
            'option'       => 'Cuba +53',
            'html'         => '<img class="flag flag-cu"/> Cuba +53',
        ),
        array(
            'id'           => 'CY+357',
            'country'      => 'Cyprus',
            'iso_2'        => 'CY',
            'calling_code' => '+357',
            'option'       => 'Cyprus +357',
            'html'         => '<img class="flag flag-cy"/> Cyprus +357',
        ),
        array(
            'id'           => 'CZ+420',
            'country'      => 'Czech Republic',
            'iso_2'        => 'CZ',
            'calling_code' => '+420',
            'option'       => 'Czech Republic +420',
            'html'         => '<img class="flag flag-cz"/> Czech Republic +420',
        ),
        array(
            'id'           => 'DK+45',
            'country'      => 'Denmark',
            'iso_2'        => 'DK',
            'calling_code' => '+45',
            'option'       => 'Denmark +45',
            'html'         => '<img class="flag flag-dk"/> Denmark +45',
        ),
        array(
            'id'           => 'DJ+253',
            'country'      => 'Djibouti',
            'iso_2'        => 'DJ',
            'calling_code' => '+253',
            'option'       => 'Djibouti +253',
            'html'         => '<img class="flag flag-dj"/> Djibouti +253',
        ),
        array(
            'id'           => 'DM+1767',
            'country'      => 'Dominica',
            'iso_2'        => 'DM',
            'calling_code' => '+1767',
            'option'       => 'Dominica +1767',
            'html'         => '<img class="flag flag-dm"/> Dominica +1767',
        ),
        array(
            'id'           => 'DO+1809',
            'country'      => 'Dominican Republic',
            'iso_2'        => 'DO',
            'calling_code' => '+1809',
            'option'       => 'Dominican Republic +1809',
            'html'         => '<img class="flag flag-do"/> Dominican Republic +1809',
        ),
        array(
            'id'           => 'EC+593',
            'country'      => 'Ecuador',
            'iso_2'        => 'EC',
            'calling_code' => '+593',
            'option'       => 'Ecuador +593',
            'html'         => '<img class="flag flag-ec"/> Ecuador +593',
        ),
        array(
            'id'           => 'EG+20',
            'country'      => 'Egypt',
            'iso_2'        => 'EG',
            'calling_code' => '+20',
            'option'       => 'Egypt +20',
            'html'         => '<img class="flag flag-eg"/> Egypt +20',
        ),
        array(
            'id'           => 'SV+503',
            'country'      => 'El Salvador',
            'iso_2'        => 'SV',
            'calling_code' => '+503',
            'option'       => 'El Salvador +503',
            'html'         => '<img class="flag flag-sv"/> El Salvador +503',
        ),
        array(
            'id'           => 'GQ+240',
            'country'      => 'Equatorial Guinea',
            'iso_2'        => 'GQ',
            'calling_code' => '+240',
            'option'       => 'Equatorial Guinea +240',
            'html'         => '<img class="flag flag-gq"/> Equatorial Guinea +240',
        ),
        array(
            'id'           => 'ER+291',
            'country'      => 'Eritrea',
            'iso_2'        => 'ER',
            'calling_code' => '+291',
            'option'       => 'Eritrea +291',
            'html'         => '<img class="flag flag-er"/> Eritrea +291',
        ),
        array(
            'id'           => 'EE+372',
            'country'      => 'Estonia',
            'iso_2'        => 'EE',
            'calling_code' => '+372',
            'option'       => 'Estonia +372',
            'html'         => '<img class="flag flag-ee"/> Estonia +372',
        ),
        array(
            'id'           => 'ET+251',
            'country'      => 'Ethiopia',
            'iso_2'        => 'ET',
            'calling_code' => '+251',
            'option'       => 'Ethiopia +251',
            'html'         => '<img class="flag flag-et"/> Ethiopia +251',
        ),
        array(
            'id'           => 'FK+500',
            'country'      => 'Falkland Islands',
            'iso_2'        => 'FK',
            'calling_code' => '+500',
            'option'       => 'Falkland Islands +500',
            'html'         => '<img class="flag flag-fk"/> Falkland Islands +500',
        ),
        array(
            'id'           => 'FO+298',
            'country'      => 'Faroe Islands',
            'iso_2'        => 'FO',
            'calling_code' => '+298',
            'option'       => 'Faroe Islands +298',
            'html'         => '<img class="flag flag-fo"/> Faroe Islands +298',
        ),
        array(
            'id'           => 'FJ+679',
            'country'      => 'Fiji',
            'iso_2'        => 'FJ',
            'calling_code' => '+679',
            'option'       => 'Fiji +679',
            'html'         => '<img class="flag flag-fj"/> Fiji +679',
        ),
        array(
            'id'           => 'FI+358',
            'country'      => 'Finland',
            'iso_2'        => 'FI',
            'calling_code' => '+358',
            'option'       => 'Finland +358',
            'html'         => '<img class="flag flag-fi"/> Finland +358',
        ),
        array(
            'id'           => 'FR+33',
            'country'      => 'France',
            'iso_2'        => 'FR',
            'calling_code' => '+33',
            'option'       => 'France +33',
            'html'         => '<img class="flag flag-fr"/> France +33',
        ),
        array(
            'id'           => 'GF+594',
            'country'      => 'French Guiana',
            'iso_2'        => 'GF',
            'calling_code' => '+594',
            'option'       => 'French Guiana +594',
            'html'         => '<img class="flag flag-gf"/> French Guiana +594',
        ),
        array(
            'id'           => 'PF+689',
            'country'      => 'French Polynesia',
            'iso_2'        => 'PF',
            'calling_code' => '+689',
            'option'       => 'French Polynesia +689',
            'html'         => '<img class="flag flag-pf"/> French Polynesia +689',
        ),
        array(
            'id'           => 'GA+241',
            'country'      => 'Gabon',
            'iso_2'        => 'GA',
            'calling_code' => '+241',
            'option'       => 'Gabon +241',
            'html'         => '<img class="flag flag-ga"/> Gabon +241',
        ),
        array(
            'id'           => 'GM+220',
            'country'      => 'Gambia',
            'iso_2'        => 'GM',
            'calling_code' => '+220',
            'option'       => 'Gambia +220',
            'html'         => '<img class="flag flag-gm"/> Gambia +220',
        ),
        array(
            'id'           => 'GE+995',
            'country'      => 'Georgia',
            'iso_2'        => 'GE',
            'calling_code' => '+995',
            'option'       => 'Georgia +995',
            'html'         => '<img class="flag flag-ge"/> Georgia +995',
        ),
        array(
            'id'           => 'DE+49',
            'country'      => 'Germany',
            'iso_2'        => 'DE',
            'calling_code' => '+49',
            'option'       => 'Germany +49',
            'html'         => '<img class="flag flag-de"/> Germany +49',
        ),
        array(
            'id'           => 'GH+233',
            'country'      => 'Ghana',
            'iso_2'        => 'GH',
            'calling_code' => '+233',
            'option'       => 'Ghana +233',
            'html'         => '<img class="flag flag-gh"/> Ghana +233',
        ),
        array(
            'id'           => 'GI+350',
            'country'      => 'Gibraltar',
            'iso_2'        => 'GI',
            'calling_code' => '+350',
            'option'       => 'Gibraltar +350',
            'html'         => '<img class="flag flag-gi"/> Gibraltar +350',
        ),
        array(
            'id'           => 'GR+30',
            'country'      => 'Greece',
            'iso_2'        => 'GR',
            'calling_code' => '+30',
            'option'       => 'Greece +30',
            'html'         => '<img class="flag flag-gr"/> Greece +30',
        ),
        array(
            'id'           => 'GL+299',
            'country'      => 'Greenland',
            'iso_2'        => 'GL',
            'calling_code' => '+299',
            'option'       => 'Greenland +299',
            'html'         => '<img class="flag flag-gl"/> Greenland +299',
        ),
        array(
            'id'           => 'GD+1473',
            'country'      => 'Grenada',
            'iso_2'        => 'GD',
            'calling_code' => '+1473',
            'option'       => 'Grenada +1473',
            'html'         => '<img class="flag flag-gd"/> Grenada +1473',
        ),
        array(
            'id'           => 'GP+590',
            'country'      => 'Guadeloupe',
            'iso_2'        => 'GP',
            'calling_code' => '+590',
            'option'       => 'Guadeloupe +590',
            'html'         => '<img class="flag flag-gp"/> Guadeloupe +590',
        ),
        array(
            'id'           => 'GU+1671',
            'country'      => 'Guam',
            'iso_2'        => 'GU',
            'calling_code' => '+1671',
            'option'       => 'Guam +1671',
            'html'         => '<img class="flag flag-gu"/> Guam +1671',
        ),
        array(
            'id'           => 'GT+502',
            'country'      => 'Guatemala',
            'iso_2'        => 'GT',
            'calling_code' => '+502',
            'option'       => 'Guatemala +502',
            'html'         => '<img class="flag flag-gt"/> Guatemala +502',
        ),
        array(
            'id'           => 'GN+224',
            'country'      => 'Guinea',
            'iso_2'        => 'GN',
            'calling_code' => '+224',
            'option'       => 'Guinea +224',
            'html'         => '<img class="flag flag-gn"/> Guinea +224',
        ),
        array(
            'id'           => 'GW+245',
            'country'      => 'Guinea Bissau',
            'iso_2'        => 'GW',
            'calling_code' => '+245',
            'option'       => 'Guinea Bissau +245',
            'html'         => '<img class="flag flag-gw"/> Guinea Bissau +245',
        ),
        array(
            'id'           => 'GY+592',
            'country'      => 'Guyana',
            'iso_2'        => 'GY',
            'calling_code' => '+592',
            'option'       => 'Guyana +592',
            'html'         => '<img class="flag flag-gy"/> Guyana +592',
        ),
        array(
            'id'           => 'HT+509',
            'country'      => 'Haiti',
            'iso_2'        => 'HT',
            'calling_code' => '+509',
            'option'       => 'Haiti +509',
            'html'         => '<img class="flag flag-ht"/> Haiti +509',
        ),
        array(
            'id'           => 'HN+504',
            'country'      => 'Honduras',
            'iso_2'        => 'HN',
            'calling_code' => '+504',
            'option'       => 'Honduras +504',
            'html'         => '<img class="flag flag-hn"/> Honduras +504',
        ),
        array(
            'id'           => 'HK+852',
            'country'      => 'Hong Kong',
            'iso_2'        => 'HK',
            'calling_code' => '+852',
            'option'       => 'Hong Kong +852',
            'html'         => '<img class="flag flag-hk"/> Hong Kong +852',
        ),
        array(
            'id'           => 'HU+36',
            'country'      => 'Hungary',
            'iso_2'        => 'HU',
            'calling_code' => '+36',
            'option'       => 'Hungary +36',
            'html'         => '<img class="flag flag-hu"/> Hungary +36',
        ),
        array(
            'id'           => 'IS+354',
            'country'      => 'Iceland',
            'iso_2'        => 'IS',
            'calling_code' => '+354',
            'option'       => 'Iceland +354',
            'html'         => '<img class="flag flag-is"/> Iceland +354',
        ),
        array(
            'id'           => 'IN+91',
            'country'      => 'India',
            'iso_2'        => 'IN',
            'calling_code' => '+91',
            'option'       => 'India +91',
            'html'         => '<img class="flag flag-in"/> India +91',
        ),
        array(
            'id'           => 'ID+62',
            'country'      => 'Indonesia',
            'iso_2'        => 'ID',
            'calling_code' => '+62',
            'option'       => 'Indonesia +62',
            'html'         => '<img class="flag flag-id"/> Indonesia +62',
        ),
        array(
            'id'           => 'IR+98',
            'country'      => 'Iran',
            'iso_2'        => 'IR',
            'calling_code' => '+98',
            'option'       => 'Iran +98',
            'html'         => '<img class="flag flag-ir"/> Iran +98',
        ),
        array(
            'id'           => 'IQ+964',
            'country'      => 'Iraq',
            'iso_2'        => 'IQ',
            'calling_code' => '+964',
            'option'       => 'Iraq +964',
            'html'         => '<img class="flag flag-iq"/> Iraq +964',
        ),
        array(
            'id'           => 'IE+353',
            'country'      => 'Ireland',
            'iso_2'        => 'IE',
            'calling_code' => '+353',
            'option'       => 'Ireland +353',
            'html'         => '<img class="flag flag-ie"/> Ireland +353',
        ),
        array(
            'id'           => 'IL+972',
            'country'      => 'Israel',
            'iso_2'        => 'IL',
            'calling_code' => '+972',
            'option'       => 'Israel +972',
            'html'         => '<img class="flag flag-il"/> Israel +972',
        ),
        array(
            'id'           => 'IT+39',
            'country'      => 'Italy',
            'iso_2'        => 'IT',
            'calling_code' => '+39',
            'option'       => 'Italy +39',
            'html'         => '<img class="flag flag-it"/> Italy +39',
        ),
        array(
            'id'           => 'JM+1876',
            'country'      => 'Jamaica',
            'iso_2'        => 'JM',
            'calling_code' => '+1876',
            'option'       => 'Jamaica +1876',
            'html'         => '<img class="flag flag-jm"/> Jamaica +1876',
        ),
        array(
            'id'           => 'JP+81',
            'country'      => 'Japan',
            'iso_2'        => 'JP',
            'calling_code' => '+81',
            'option'       => 'Japan +81',
            'html'         => '<img class="flag flag-jp"/> Japan +81',
        ),
        array(
            'id'           => 'JO+962',
            'country'      => 'Jordan',
            'iso_2'        => 'JO',
            'calling_code' => '+962',
            'option'       => 'Jordan +962',
            'html'         => '<img class="flag flag-jo"/> Jordan +962',
        ),
        array(
            'id'           => 'KZ+7',
            'country'      => 'Kazakhstan',
            'iso_2'        => 'KZ',
            'calling_code' => '+7',
            'option'       => 'Kazakhstan +7',
            'html'         => '<img class="flag flag-kz"/> Kazakhstan +7',
        ),
        array(
            'id'           => 'KE+254',
            'country'      => 'Kenya',
            'iso_2'        => 'KE',
            'calling_code' => '+254',
            'option'       => 'Kenya +254',
            'html'         => '<img class="flag flag-ke"/> Kenya +254',
        ),
        array(
            'id'           => 'KI+686',
            'country'      => 'Kiribati',
            'iso_2'        => 'KI',
            'calling_code' => '+686',
            'option'       => 'Kiribati +686',
            'html'         => '<img class="flag flag-ki"/> Kiribati +686',
        ),
        array(
            'id'           => 'KP+850',
            'country'      => 'North Korea',
            'iso_2'        => 'KP',
            'calling_code' => '+850',
            'option'       => 'North Korea +850',
            'html'         => '<img class="flag flag-kp"/> North Korea +850',
        ),
        array(
            'id'           => '82+82',
            'country'      => 'South Korea',
            'iso_2'        => '82',
            'calling_code' => '+82',
            'option'       => 'South Korea +82',
            'html'         => '<img class="flag flag-82"/> South Korea +82',
        ),
        array(
            'id'           => 'KW+965',
            'country'      => 'Kuwait',
            'iso_2'        => 'KW',
            'calling_code' => '+965',
            'option'       => 'Kuwait +965',
            'html'         => '<img class="flag flag-kw"/> Kuwait +965',
        ),
        array(
            'id'           => 'KG+996',
            'country'      => 'Kyrgyzstan',
            'iso_2'        => 'KG',
            'calling_code' => '+996',
            'option'       => 'Kyrgyzstan +996',
            'html'         => '<img class="flag flag-kg"/> Kyrgyzstan +996',
        ),
        array(
            'id'           => 'LA+856',
            'country'      => 'Laos',
            'iso_2'        => 'LA',
            'calling_code' => '+856',
            'option'       => 'Laos +856',
            'html'         => '<img class="flag flag-la"/> Laos +856',
        ),
        array(
            'id'           => 'LV+371',
            'country'      => 'Latvia',
            'iso_2'        => 'LV',
            'calling_code' => '+371',
            'option'       => 'Latvia +371',
            'html'         => '<img class="flag flag-lv"/> Latvia +371',
        ),
        array(
            'id'           => 'LB+961',
            'country'      => 'Lebanon',
            'iso_2'        => 'LB',
            'calling_code' => '+961',
            'option'       => 'Lebanon +961',
            'html'         => '<img class="flag flag-lb"/> Lebanon +961',
        ),
        array(
            'id'           => 'LS+266',
            'country'      => 'Lesotho',
            'iso_2'        => 'LS',
            'calling_code' => '+266',
            'option'       => 'Lesotho +266',
            'html'         => '<img class="flag flag-ls"/> Lesotho +266',
        ),
        array(
            'id'           => 'LR+231',
            'country'      => 'Liberia',
            'iso_2'        => 'LR',
            'calling_code' => '+231',
            'option'       => 'Liberia +231',
            'html'         => '<img class="flag flag-lr"/> Liberia +231',
        ),
        array(
            'id'           => 'LY+218',
            'country'      => 'Libya',
            'iso_2'        => 'LY',
            'calling_code' => '+218',
            'option'       => 'Libya +218',
            'html'         => '<img class="flag flag-ly"/> Libya +218',
        ),
        array(
            'id'           => 'LI+423',
            'country'      => 'Liechtenstein',
            'iso_2'        => 'LI',
            'calling_code' => '+423',
            'option'       => 'Liechtenstein +423',
            'html'         => '<img class="flag flag-li"/> Liechtenstein +423',
        ),
        array(
            'id'           => 'LT+370',
            'country'      => 'Lithuania',
            'iso_2'        => 'LT',
            'calling_code' => '+370',
            'option'       => 'Lithuania +370',
            'html'         => '<img class="flag flag-lt"/> Lithuania +370',
        ),
        array(
            'id'           => 'LU+352',
            'country'      => 'Luxembourg',
            'iso_2'        => 'LU',
            'calling_code' => '+352',
            'option'       => 'Luxembourg +352',
            'html'         => '<img class="flag flag-lu"/> Luxembourg +352',
        ),
        array(
            'id'           => 'MO+853',
            'country'      => 'Macau',
            'iso_2'        => 'MO',
            'calling_code' => '+853',
            'option'       => 'Macau +853',
            'html'         => '<img class="flag flag-mo"/> Macau +853',
        ),
        array(
            'id'           => 'MK+389',
            'country'      => 'Macedonia',
            'iso_2'        => 'MK',
            'calling_code' => '+389',
            'option'       => 'Macedonia +389',
            'html'         => '<img class="flag flag-mk"/> Macedonia +389',
        ),
        array(
            'id'           => 'MG+261',
            'country'      => 'Madagascar',
            'iso_2'        => 'MG',
            'calling_code' => '+261',
            'option'       => 'Madagascar +261',
            'html'         => '<img class="flag flag-mg"/> Madagascar +261',
        ),
        array(
            'id'           => 'MW+265',
            'country'      => 'Malawi',
            'iso_2'        => 'MW',
            'calling_code' => '+265',
            'option'       => 'Malawi +265',
            'html'         => '<img class="flag flag-mw"/> Malawi +265',
        ),
        array(
            'id'           => 'MY+60',
            'country'      => 'Malaysia',
            'iso_2'        => 'MY',
            'calling_code' => '+60',
            'option'       => 'Malaysia +60',
            'html'         => '<img class="flag flag-my"/> Malaysia +60',
        ),
        array(
            'id'           => 'MV+960',
            'country'      => 'Maldives',
            'iso_2'        => 'MV',
            'calling_code' => '+960',
            'option'       => 'Maldives +960',
            'html'         => '<img class="flag flag-mv"/> Maldives +960',
        ),
        array(
            'id'           => 'ML+223',
            'country'      => 'Mali',
            'iso_2'        => 'ML',
            'calling_code' => '+223',
            'option'       => 'Mali +223',
            'html'         => '<img class="flag flag-ml"/> Mali +223',
        ),
        array(
            'id'           => 'MT+356',
            'country'      => 'Malta',
            'iso_2'        => 'MT',
            'calling_code' => '+356',
            'option'       => 'Malta +356',
            'html'         => '<img class="flag flag-mt"/> Malta +356',
        ),
        array(
            'id'           => 'MH+692',
            'country'      => 'Marshall Islands',
            'iso_2'        => 'MH',
            'calling_code' => '+692',
            'option'       => 'Marshall Islands +692',
            'html'         => '<img class="flag flag-mh"/> Marshall Islands +692',
        ),
        array(
            'id'           => 'MQ+596',
            'country'      => 'Martinique',
            'iso_2'        => 'MQ',
            'calling_code' => '+596',
            'option'       => 'Martinique +596',
            'html'         => '<img class="flag flag-mq"/> Martinique +596',
        ),
        array(
            'id'           => 'MR+222',
            'country'      => 'Mauritania',
            'iso_2'        => 'MR',
            'calling_code' => '+222',
            'option'       => 'Mauritania +222',
            'html'         => '<img class="flag flag-mr"/> Mauritania +222',
        ),
        array(
            'id'           => 'MU+230',
            'country'      => 'Mauritius',
            'iso_2'        => 'MU',
            'calling_code' => '+230',
            'option'       => 'Mauritius +230',
            'html'         => '<img class="flag flag-mu"/> Mauritius +230',
        ),
        array(
            'id'           => 'MX+52',
            'country'      => 'Mexico',
            'iso_2'        => 'MX',
            'calling_code' => '+52',
            'option'       => 'Mexico +52',
            'html'         => '<img class="flag flag-mx"/> Mexico +52',
        ),
        array(
            'id'           => 'FM+691',
            'country'      => 'Micronesia',
            'iso_2'        => 'FM',
            'calling_code' => '+691',
            'option'       => 'Micronesia +691',
            'html'         => '<img class="flag flag-fm"/> Micronesia +691',
        ),
        array(
            'id'           => 'MD+373',
            'country'      => 'Moldova',
            'iso_2'        => 'MD',
            'calling_code' => '+373',
            'option'       => 'Moldova +373',
            'html'         => '<img class="flag flag-md"/> Moldova +373',
        ),
        array(
            'id'           => 'MC+377',
            'country'      => 'Monaco',
            'iso_2'        => 'MC',
            'calling_code' => '+377',
            'option'       => 'Monaco +377',
            'html'         => '<img class="flag flag-mc"/> Monaco +377',
        ),
        array(
            'id'           => 'MN+976',
            'country'      => 'Mongolia',
            'iso_2'        => 'MN',
            'calling_code' => '+976',
            'option'       => 'Mongolia +976',
            'html'         => '<img class="flag flag-mn"/> Mongolia +976',
        ),
        array(
            'id'           => 'MS+1664',
            'country'      => 'Montserrat',
            'iso_2'        => 'MS',
            'calling_code' => '+1664',
            'option'       => 'Montserrat +1664',
            'html'         => '<img class="flag flag-ms"/> Montserrat +1664',
        ),
        array(
            'id'           => 'MA+212',
            'country'      => 'Morocco',
            'iso_2'        => 'MA',
            'calling_code' => '+212',
            'option'       => 'Morocco +212',
            'html'         => '<img class="flag flag-ma"/> Morocco +212',
        ),
        array(
            'id'           => 'MZ+258',
            'country'      => 'Mozambique',
            'iso_2'        => 'MZ',
            'calling_code' => '+258',
            'option'       => 'Mozambique +258',
            'html'         => '<img class="flag flag-mz"/> Mozambique +258',
        ),
        array(
            'id'           => 'MM+95',
            'country'      => 'Myanmar',
            'iso_2'        => 'MM',
            'calling_code' => '+95',
            'option'       => 'Myanmar +95',
            'html'         => '<img class="flag flag-mm"/> Myanmar +95',
        ),
        array(
            'id'           => 'NA+264',
            'country'      => 'Namibia',
            'iso_2'        => 'NA',
            'calling_code' => '+264',
            'option'       => 'Namibia +264',
            'html'         => '<img class="flag flag-na"/> Namibia +264',
        ),
        array(
            'id'           => 'NR+674',
            'country'      => 'Nauru',
            'iso_2'        => 'NR',
            'calling_code' => '+674',
            'option'       => 'Nauru +674',
            'html'         => '<img class="flag flag-nr"/> Nauru +674',
        ),
        array(
            'id'           => 'NP+977',
            'country'      => 'Nepal',
            'iso_2'        => 'NP',
            'calling_code' => '+977',
            'option'       => 'Nepal +977',
            'html'         => '<img class="flag flag-np"/> Nepal +977',
        ),
        array(
            'id'           => 'NL+31',
            'country'      => 'Netherlands',
            'iso_2'        => 'NL',
            'calling_code' => '+31',
            'option'       => 'Netherlands +31',
            'html'         => '<img class="flag flag-nl"/> Netherlands +31',
        ),
        array(
            'id'           => 'NC+687',
            'country'      => 'New Caledonia',
            'iso_2'        => 'NC',
            'calling_code' => '+687',
            'option'       => 'New Caledonia +687',
            'html'         => '<img class="flag flag-nc"/> New Caledonia +687',
        ),
        array(
            'id'           => 'NZ+64',
            'country'      => 'New Zealand',
            'iso_2'        => 'NZ',
            'calling_code' => '+64',
            'option'       => 'New Zealand +64',
            'html'         => '<img class="flag flag-nz"/> New Zealand +64',
        ),
        array(
            'id'           => 'NI+505',
            'country'      => 'Nicaragua',
            'iso_2'        => 'NI',
            'calling_code' => '+505',
            'option'       => 'Nicaragua +505',
            'html'         => '<img class="flag flag-ni"/> Nicaragua +505',
        ),
        array(
            'id'           => 'NE+227',
            'country'      => 'Niger',
            'iso_2'        => 'NE',
            'calling_code' => '+227',
            'option'       => 'Niger +227',
            'html'         => '<img class="flag flag-ne"/> Niger +227',
        ),
        array(
            'id'           => 'NG+234',
            'country'      => 'Nigeria',
            'iso_2'        => 'NG',
            'calling_code' => '+234',
            'option'       => 'Nigeria +234',
            'html'         => '<img class="flag flag-ng"/> Nigeria +234',
        ),
        array(
            'id'           => 'NU+683',
            'country'      => 'Niue',
            'iso_2'        => 'NU',
            'calling_code' => '+683',
            'option'       => 'Niue +683',
            'html'         => '<img class="flag flag-nu"/> Niue +683',
        ),
        array(
            'id'           => 'NF+6723',
            'country'      => 'Norfolk Island',
            'iso_2'        => 'NF',
            'calling_code' => '+6723',
            'option'       => 'Norfolk Island +6723',
            'html'         => '<img class="flag flag-nf"/> Norfolk Island +6723',
        ),
        array(
            'id'           => 'MP+1',
            'country'      => 'Northern Mariana Islands',
            'iso_2'        => 'MP',
            'calling_code' => '+1',
            'option'       => 'Northern Mariana Islands +1',
            'html'         => '<img class="flag flag-mp"/> Northern Mariana Islands +1',
        ),
        array(
            'id'           => 'NO+47',
            'country'      => 'Norway',
            'iso_2'        => 'NO',
            'calling_code' => '+47',
            'option'       => 'Norway +47',
            'html'         => '<img class="flag flag-no"/> Norway +47',
        ),
        array(
            'id'           => 'OM+968',
            'country'      => 'Oman',
            'iso_2'        => 'OM',
            'calling_code' => '+968',
            'option'       => 'Oman +968',
            'html'         => '<img class="flag flag-om"/> Oman +968',
        ),
        array(
            'id'           => 'PK+92',
            'country'      => 'Pakistan',
            'iso_2'        => 'PK',
            'calling_code' => '+92',
            'option'       => 'Pakistan +92',
            'html'         => '<img class="flag flag-pk"/> Pakistan +92',
        ),
        array(
            'id'           => 'PW+680',
            'country'      => 'Palau',
            'iso_2'        => 'PW',
            'calling_code' => '+680',
            'option'       => 'Palau +680',
            'html'         => '<img class="flag flag-pw"/> Palau +680',
        ),
        array(
            'id'           => 'PA+507',
            'country'      => 'Panama',
            'iso_2'        => 'PA',
            'calling_code' => '+507',
            'option'       => 'Panama +507',
            'html'         => '<img class="flag flag-pa"/> Panama +507',
        ),
        array(
            'id'           => 'PG+675',
            'country'      => 'Papua New Guinea',
            'iso_2'        => 'PG',
            'calling_code' => '+675',
            'option'       => 'Papua New Guinea +675',
            'html'         => '<img class="flag flag-pg"/> Papua New Guinea +675',
        ),
        array(
            'id'           => 'PY+595',
            'country'      => 'Paraguay',
            'iso_2'        => 'PY',
            'calling_code' => '+595',
            'option'       => 'Paraguay +595',
            'html'         => '<img class="flag flag-py"/> Paraguay +595',
        ),
        array(
            'id'           => 'PE+51',
            'country'      => 'Peru',
            'iso_2'        => 'PE',
            'calling_code' => '+51',
            'option'       => 'Peru +51',
            'html'         => '<img class="flag flag-pe"/> Peru +51',
        ),
        array(
            'id'           => 'PH+63',
            'country'      => 'Philippines',
            'iso_2'        => 'PH',
            'calling_code' => '+63',
            'option'       => 'Philippines +63',
            'html'         => '<img class="flag flag-ph"/> Philippines +63',
        ),
        array(
            'id'           => 'PL+48',
            'country'      => 'Poland',
            'iso_2'        => 'PL',
            'calling_code' => '+48',
            'option'       => 'Poland +48',
            'html'         => '<img class="flag flag-pl"/> Poland +48',
        ),
        array(
            'id'           => 'PT+351',
            'country'      => 'Portugal',
            'iso_2'        => 'PT',
            'calling_code' => '+351',
            'option'       => 'Portugal +351',
            'html'         => '<img class="flag flag-pt"/> Portugal +351',
        ),
        array(
            'id'           => 'PR+1787',
            'country'      => 'Puerto Rico',
            'iso_2'        => 'PR',
            'calling_code' => '+1787',
            'option'       => 'Puerto Rico +1787',
            'html'         => '<img class="flag flag-pr"/> Puerto Rico +1787',
        ),
        array(
            'id'           => 'QA+974',
            'country'      => 'Qatar',
            'iso_2'        => 'QA',
            'calling_code' => '+974',
            'option'       => 'Qatar +974',
            'html'         => '<img class="flag flag-qa"/> Qatar +974',
        ),
        array(
            'id'           => 'RE+262',
            'country'      => 'Reunion',
            'iso_2'        => 'RE',
            'calling_code' => '+262',
            'option'       => 'Reunion +262',
            'html'         => '<img class="flag flag-re"/> Reunion +262',
        ),
        array(
            'id'           => 'RO+40',
            'country'      => 'Romania',
            'iso_2'        => 'RO',
            'calling_code' => '+40',
            'option'       => 'Romania +40',
            'html'         => '<img class="flag flag-ro"/> Romania +40',
        ),
        array(
            'id'           => 'RU+7',
            'country'      => 'Russia',
            'iso_2'        => 'RU',
            'calling_code' => '+7',
            'option'       => 'Russia +7',
            'html'         => '<img class="flag flag-ru"/> Russia +7',
        ),
        array(
            'id'           => 'RW+250',
            'country'      => 'Rwanda',
            'iso_2'        => 'RW',
            'calling_code' => '+250',
            'option'       => 'Rwanda +250',
            'html'         => '<img class="flag flag-rw"/> Rwanda +250',
        ),
        array(
            'id'           => 'KN+1869',
            'country'      => 'Saint Kitts and Nevis',
            'iso_2'        => 'KN',
            'calling_code' => '+1869',
            'option'       => 'Saint Kitts and Nevis +1869',
            'html'         => '<img class="flag flag-kn"/> Saint Kitts and Nevis +1869',
        ),
        array(
            'id'           => 'LC+1758',
            'country'      => 'Saint Lucia',
            'iso_2'        => 'LC',
            'calling_code' => '+1758',
            'option'       => 'Saint Lucia +1758',
            'html'         => '<img class="flag flag-lc"/> Saint Lucia +1758',
        ),
        array(
            'id'           => 'WS+685',
            'country'      => 'Samoa',
            'iso_2'        => 'WS',
            'calling_code' => '+685',
            'option'       => 'Samoa +685',
            'html'         => '<img class="flag flag-ws"/> Samoa +685',
        ),
        array(
            'id'           => 'SM+378',
            'country'      => 'San Marino',
            'iso_2'        => 'SM',
            'calling_code' => '+378',
            'option'       => 'San Marino +378',
            'html'         => '<img class="flag flag-sm"/> San Marino +378',
        ),
        array(
            'id'           => 'ST+239',
            'country'      => 'Sao Tome and Principe',
            'iso_2'        => 'ST',
            'calling_code' => '+239',
            'option'       => 'Sao Tome and Principe +239',
            'html'         => '<img class="flag flag-st"/> Sao Tome and Principe +239',
        ),
        array(
            'id'           => 'SA+966',
            'country'      => 'Saudi Arabia',
            'iso_2'        => 'SA',
            'calling_code' => '+966',
            'option'       => 'Saudi Arabia +966',
            'html'         => '<img class="flag flag-sa"/> Saudi Arabia +966',
        ),
        array(
            'id'           => 'SN+221',
            'country'      => 'Senegal',
            'iso_2'        => 'SN',
            'calling_code' => '+221',
            'option'       => 'Senegal +221',
            'html'         => '<img class="flag flag-sn"/> Senegal +221',
        ),
        array(
            'id'           => 'SC+248',
            'country'      => 'Seychelles',
            'iso_2'        => 'SC',
            'calling_code' => '+248',
            'option'       => 'Seychelles +248',
            'html'         => '<img class="flag flag-sc"/> Seychelles +248',
        ),
        array(
            'id'           => 'SL+232',
            'country'      => 'Sierra Leone',
            'iso_2'        => 'SL',
            'calling_code' => '+232',
            'option'       => 'Sierra Leone +232',
            'html'         => '<img class="flag flag-sl"/> Sierra Leone +232',
        ),
        array(
            'id'           => 'SG+65',
            'country'      => 'Singapore',
            'iso_2'        => 'SG',
            'calling_code' => '+65',
            'option'       => 'Singapore +65',
            'html'         => '<img class="flag flag-sg"/> Singapore +65',
        ),
        array(
            'id'           => 'SK+421',
            'country'      => 'Slovakia',
            'iso_2'        => 'SK',
            'calling_code' => '+421',
            'option'       => 'Slovakia +421',
            'html'         => '<img class="flag flag-sk"/> Slovakia +421',
        ),
        array(
            'id'           => 'SI+386',
            'country'      => 'Slovenia',
            'iso_2'        => 'SI',
            'calling_code' => '+386',
            'option'       => 'Slovenia +386',
            'html'         => '<img class="flag flag-si"/> Slovenia +386',
        ),
        array(
            'id'           => 'SB+677',
            'country'      => 'Solomon Islands',
            'iso_2'        => 'SB',
            'calling_code' => '+677',
            'option'       => 'Solomon Islands +677',
            'html'         => '<img class="flag flag-sb"/> Solomon Islands +677',
        ),
        array(
            'id'           => 'SO+252',
            'country'      => 'Somalia',
            'iso_2'        => 'SO',
            'calling_code' => '+252',
            'option'       => 'Somalia +252',
            'html'         => '<img class="flag flag-so"/> Somalia +252',
        ),
        array(
            'id'           => 'ZA+27',
            'country'      => 'South Africa',
            'iso_2'        => 'ZA',
            'calling_code' => '+27',
            'option'       => 'South Africa +27',
            'html'         => '<img class="flag flag-za"/> South Africa +27',
        ),
        array(
            'id'           => '211+211',
            'country'      => 'South Sudan',
            'iso_2'        => '211',
            'calling_code' => '+211',
            'option'       => 'South Sudan +211',
            'html'         => '<img class="flag flag-211"/> South Sudan +211',
        ),
        array(
            'id'           => 'ES+34',
            'country'      => 'Spain',
            'iso_2'        => 'ES',
            'calling_code' => '+34',
            'option'       => 'Spain +34',
            'html'         => '<img class="flag flag-es"/> Spain +34',
        ),
        array(
            'id'           => 'LK+94',
            'country'      => 'Sri Lanka',
            'iso_2'        => 'LK',
            'calling_code' => '+94',
            'option'       => 'Sri Lanka +94',
            'html'         => '<img class="flag flag-lk"/> Sri Lanka +94',
        ),
        array(
            'id'           => 'SD+249',
            'country'      => 'Sudan',
            'iso_2'        => 'SD',
            'calling_code' => '+249',
            'option'       => 'Sudan +249',
            'html'         => '<img class="flag flag-sd"/> Sudan +249',
        ),
        array(
            'id'           => 'SR+597',
            'country'      => 'Suriname',
            'iso_2'        => 'SR',
            'calling_code' => '+597',
            'option'       => 'Suriname +597',
            'html'         => '<img class="flag flag-sr"/> Suriname +597',
        ),
        array(
            'id'           => 'SZ+268',
            'country'      => 'Swaziland',
            'iso_2'        => 'SZ',
            'calling_code' => '+268',
            'option'       => 'Swaziland +268',
            'html'         => '<img class="flag flag-sz"/> Swaziland +268',
        ),
        array(
            'id'           => 'SE+46',
            'country'      => 'Sweden',
            'iso_2'        => 'SE',
            'calling_code' => '+46',
            'option'       => 'Sweden +46',
            'html'         => '<img class="flag flag-se"/> Sweden +46',
        ),
        array(
            'id'           => 'CH+41',
            'country'      => 'Switzerland',
            'iso_2'        => 'CH',
            'calling_code' => '+41',
            'option'       => 'Switzerland +41',
            'html'         => '<img class="flag flag-ch"/> Switzerland +41',
        ),
        array(
            'id'           => 'SY+963',
            'country'      => 'Syria',
            'iso_2'        => 'SY',
            'calling_code' => '+963',
            'option'       => 'Syria +963',
            'html'         => '<img class="flag flag-sy"/> Syria +963',
        ),
        array(
            'id'           => 'TW+886',
            'country'      => 'Taiwan',
            'iso_2'        => 'TW',
            'calling_code' => '+886',
            'option'       => 'Taiwan +886',
            'html'         => '<img class="flag flag-tw"/> Taiwan +886',
        ),
        array(
            'id'           => 'TJ+992',
            'country'      => 'Tajikistan',
            'iso_2'        => 'TJ',
            'calling_code' => '+992',
            'option'       => 'Tajikistan +992',
            'html'         => '<img class="flag flag-tj"/> Tajikistan +992',
        ),
        array(
            'id'           => 'TZ+255',
            'country'      => 'Tanzania',
            'iso_2'        => 'TZ',
            'calling_code' => '+255',
            'option'       => 'Tanzania +255',
            'html'         => '<img class="flag flag-tz"/> Tanzania +255',
        ),
        array(
            'id'           => 'TH+66',
            'country'      => 'Thailand',
            'iso_2'        => 'TH',
            'calling_code' => '+66',
            'option'       => 'Thailand +66',
            'html'         => '<img class="flag flag-th"/> Thailand +66',
        ),
        array(
            'id'           => 'TP+670',
            'country'      => 'East Timor',
            'iso_2'        => 'TP',
            'calling_code' => '+670',
            'option'       => 'East Timor +670',
            'html'         => '<img class="flag flag-tp"/> East Timor +670',
        ),
        array(
            'id'           => 'TG+228',
            'country'      => 'Togo',
            'iso_2'        => 'TG',
            'calling_code' => '+228',
            'option'       => 'Togo +228',
            'html'         => '<img class="flag flag-tg"/> Togo +228',
        ),
        array(
            'id'           => 'TK+690',
            'country'      => 'Tokelau',
            'iso_2'        => 'TK',
            'calling_code' => '+690',
            'option'       => 'Tokelau +690',
            'html'         => '<img class="flag flag-tk"/> Tokelau +690',
        ),
        array(
            'id'           => 'TO+676',
            'country'      => 'Tonga',
            'iso_2'        => 'TO',
            'calling_code' => '+676',
            'option'       => 'Tonga +676',
            'html'         => '<img class="flag flag-to"/> Tonga +676',
        ),
        array(
            'id'           => 'TT+1868',
            'country'      => 'Trinidad and Tobago',
            'iso_2'        => 'TT',
            'calling_code' => '+1868',
            'option'       => 'Trinidad and Tobago +1868',
            'html'         => '<img class="flag flag-tt"/> Trinidad and Tobago +1868',
        ),
        array(
            'id'           => 'TN+216',
            'country'      => 'Tunisia',
            'iso_2'        => 'TN',
            'calling_code' => '+216',
            'option'       => 'Tunisia +216',
            'html'         => '<img class="flag flag-tn"/> Tunisia +216',
        ),
        array(
            'id'           => 'TR+90',
            'country'      => 'Turkey',
            'iso_2'        => 'TR',
            'calling_code' => '+90',
            'option'       => 'Turkey +90',
            'html'         => '<img class="flag flag-tr"/> Turkey +90',
        ),
        array(
            'id'           => 'TM+993',
            'country'      => 'Turkmenistan',
            'iso_2'        => 'TM',
            'calling_code' => '+993',
            'option'       => 'Turkmenistan +993',
            'html'         => '<img class="flag flag-tm"/> Turkmenistan +993',
        ),
        array(
            'id'           => 'TC+1649',
            'country'      => 'Turks and Caicos',
            'iso_2'        => 'TC',
            'calling_code' => '+1649',
            'option'       => 'Turks and Caicos +1649',
            'html'         => '<img class="flag flag-tc"/> Turks and Caicos +1649',
        ),
        array(
            'id'           => 'TV+688',
            'country'      => 'Tuvalu',
            'iso_2'        => 'TV',
            'calling_code' => '+688',
            'option'       => 'Tuvalu +688',
            'html'         => '<img class="flag flag-tv"/> Tuvalu +688',
        ),
        array(
            'id'           => 'UG+256',
            'country'      => 'Uganda',
            'iso_2'        => 'UG',
            'calling_code' => '+256',
            'option'       => 'Uganda +256',
            'html'         => '<img class="flag flag-ug"/> Uganda +256',
        ),
        array(
            'id'           => 'UA+380',
            'country'      => 'Ukraine',
            'iso_2'        => 'UA',
            'calling_code' => '+380',
            'option'       => 'Ukraine +380',
            'html'         => '<img class="flag flag-ua"/> Ukraine +380',
        ),
        array(
            'id'           => 'AE+971',
            'country'      => 'United Arab Emirates',
            'iso_2'        => 'AE',
            'calling_code' => '+971',
            'option'       => 'United Arab Emirates +971',
            'html'         => '<img class="flag flag-ae"/> United Arab Emirates +971',
        ),
        array(
            'country'      => 'United Kingdom',
            'iso_2'        => 'GB',
            'calling_code' => '+44',
            'option'       => 'United Kingdom +44',
            'html'         => '<img class="flag flag-gb"/> United Kingdom +44',
        ),
        array(
            'country'      => 'United States',
            'iso_2'        => 'US',
            'calling_code' => '+1',
            'option'       => 'United States +1',
            'html'         => '<img class="flag flag-us"/> United States +1',
        ),
        array(
            'country'      => 'Uruguay',
            'iso_2'        => 'UY',
            'calling_code' => '+598',
            'option'       => 'Uruguay +598',
            'html'         => '<img class="flag flag-uy"/> Uruguay +598',
        ),
        array(
            'country'      => 'Uzbekistan',
            'iso_2'        => 'UZ',
            'calling_code' => '+998',
            'option'       => 'Uzbekistan +998',
            'html'         => '<img class="flag flag-uz"/> Uzbekistan +998',
        ),
        array(
            'country'      => 'Vanuatu',
            'iso_2'        => 'VU',
            'calling_code' => '+678',
            'option'       => 'Vanuatu +678',
            'html'         => '<img class="flag flag-vu"/> Vanuatu +678',
        ),
        array(
            'country'      => 'Vatican City',
            'iso_2'        => 'VA',
            'calling_code' => '+379',
            'option'       => 'Vatican City +379',
            'html'         => '<img class="flag flag-va"/> Vatican City +379',
        ),
        array(
            'country'      => 'Venezuela',
            'iso_2'        => 'VE',
            'calling_code' => '+58',
            'option'       => 'Venezuela +58',
            'html'         => '<img class="flag flag-ve"/> Venezuela +58',
        ),
        array(
            'country'      => 'Vietnam',
            'iso_2'        => 'VN',
            'calling_code' => '+84',
            'option'       => 'Vietnam +84',
            'html'         => '<img class="flag flag-vn"/> Vietnam +84',
        ),
        array(
            'country'      => 'Virgin Islands (British)',
            'iso_2'        => 'VG',
            'calling_code' => '+1284',
            'option'       => 'Virgin Islands (British) +1284',
            'html'         => '<img class="flag flag-vg"/> Virgin Islands (British) +1284',
        ),
        array(
            'country'      => 'Virgin Islands (US)',
            'iso_2'        => 'VI',
            'calling_code' => '+1340',
            'option'       => 'Virgin Islands (US) +1340',
            'html'         => '<img class="flag flag-vi"/> Virgin Islands (US) +1340',
        ),
        array(
            'country'      => 'Wallis and Futuna',
            'iso_2'        => 'WF',
            'calling_code' => '+681',
            'option'       => 'Wallis and Futuna +681',
            'html'         => '<img class="flag flag-wf"/> Wallis and Futuna +681',
        ),
        array(
            'country'      => 'Yemen',
            'iso_2'        => 'YE',
            'calling_code' => '+967',
            'option'       => 'Yemen +967',
            'html'         => '<img class="flag flag-ye"/> Yemen +967',
        ),
        array(
            'country'      => 'Zambia',
            'iso_2'        => 'ZM',
            'calling_code' => '+260',
            'option'       => 'Zambia +260',
            'html'         => '<img class="flag flag-zm"/> Zambia +260',
        ),
        array(
            'country'      => 'Zimbabwe',
            'iso_2'        => 'ZW',
            'calling_code' => '+263',
            'option'       => 'Zimbabwe +263',
            'html'         => '<img class="flag flag-zw"/> Zimbabwe +263',
        ),
    );

    /**
     * Pre save
     *
     * @return void
     */
    public function preSave()
    {
        return preg_replace('/[^0-9]/', '', $this->value);
    }
}
